"""add role enum

Revision ID: 5e91b178b503
Revises: 19fadf2621ab
Create Date: 2024-12-16 22:38:34.931518

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5e91b178b503"
down_revision: Union[str, None] = "19fadf2621ab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the Enum type
    user_role_enum = sa.Enum("USER", "ADMIN", name="user_role")
    user_role_enum.create(op.get_bind())

    # Add the column using the Enum type
    op.add_column(
        "users",
        sa.Column("role", user_role_enum, nullable=False, server_default="USER"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the column
    op.drop_column("users", "role")

    # Drop the Enum type
    user_role_enum = sa.Enum("USER", "ADMIN", name="user_role")
    user_role_enum.drop(op.get_bind())
    # ### end Alembic commands ###
